theme: jekyll-theme-minimal
title: Hi, I'm Hanne!
description: <br> A statistician interested in data visualization, interdisciplinarity, and open science. <br> Follow me on [Twitter](https://twitter.com/hioberman) if you want to get to know me (and my terrible sense of academia/programming humor).
logo: /img/avatar.png
