theme: jekyll-theme-minimal
title: Hi, I'm Hanne!  <br>
description: <br> A statistician interested in data visualization, interdisciplinarity, and open science. <br> <br> Follow me on <a href="https://twitter.com/hioberman">Twitter</a> if you want to get to know me (and my terrible sense of humor about programming, academia, and more).  <br> <br> Or contact me at h.i.oberman@uu.nl.  <br> <br> 
logo: /img/avatar.png
